branch-defaults:
  main:
    environment: null
global:
  application_name: Machine_Learning
  branch: main
  default_ec2_keyname: null
  default_platform: Python 3.7
  default_region: Tokyo
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: origin
  sc: git
  workspace_type: Application